dbmi-bgm/cgap-portal

- src/encoded/authorization.py
- src/encoded/schemas/case.json
- src/encoded/schemas/disease.json
- src/encoded/schemas/individual.json
- src/encoded/schemas/phenotype.json
- src/encoded/schemas/sample.json
- src/encoded/schemas/user.json
- src/encoded/tests/data/inserts/case.json
- src/encoded/tests/data/inserts/individual.json
- src/encoded/tests/data/inserts/sample.json
- src/encoded/types/__init__.py
Preliminary clinical data model that is by no means complete. Other tasks in progress:
- Refinement of HPO schemas and loading HPO terms (Andy)
- Putting schemas in a spreadsheet for easier editing/display and creating visual model (Koray)
- Test data (Luisa)
> Clinical data model

- .travis.yml
- buildout.cfg
- src/encoded/tests/test_fixtures.py
- src/encoded/types/base.py
- src/encoded/types/user_content.py
Simple PR to add `item_type` to item classes used in abstract collections so that the /profiles/ page can correctly display them. Also use the `@abstract_collection` decorator for the base Item
> Abstract types cgap

- .ebextensions/05_set_wsgi.config
- .ebextensions/09_cloudwatch.config
- .ebextensions/11_logs.config
- .ebextensions/12_daily_restart.config
- .ebextensions/20_packages.config
- .ebextensions/encoded-apache.conf
- base.ini
- buildout.cfg
- src/encoded/memlimit.py
See: https://github.com/4dn-dcic/fourfront/pull/1162
> Apache server config

- src/encoded/static/components/item-pages/UserView.js
- Same access key fix from Fourfront 1171
> access key bug fix

- setup.py
- src/encoded/commands/generate_items_from_owl.py
- src/encoded/commands/load_items.py
- src/encoded/commands/owltools.py
- src/encoded/commands/parse_hpoa.py
- src/encoded/tests/test_owltools.py
For this iteration simply added scripts to command directory as is,  Will tweak later to add tracking output.  These currently need to be run locally.
Added back scripts to command.
Updated setup.py
> Add back scripts

- buildout.cfg
- src/encoded/search.py
- src/encoded/tests/data/workbook-inserts/file_fastq.json
- src/encoded/tests/data/workbook-inserts/file_format.json
- src/encoded/tests/data/workbook-inserts/individual.json
- src/encoded/tests/test_search.py
- src/encoded/types/cohort.py
- versions.cfg
Sort correctly on date fields that are not top-level. Also incorporates changes from the following Fourfront PR: https://github.com/4dn-dcic/fourfront/pull/1198
Some other misc. changes and insert changes to get tests running
> Sort by date

- buildout.cfg
- src/encoded/search.py
- src/encoded/tests/data/master-inserts/user.json
- src/encoded/tests/test_search.py
- Add some tests to verify our new ES setup is working properly
- Snovault release is up
- DB's have been updated for transaction table deprecation
> Sno-115 Tests

- src/encoded/commands/create_mapping_on_deploy.py
- src/encoded/tests/test_create_mapping.py
- Port https://github.com/4dn-dcic/fourfront/pull/1237
- Customized slightly for CGAP needs but probably not fully fleshed out
> Deploy Change

- src/encoded/loadxl.py
- src/encoded/server_defaults.py
- src/encoded/tests/data/master-inserts/user.json
- src/encoded/tests/data/workbook-inserts/user.json
- src/encoded/types/base.py
- Port https://github.com/4dn-dcic/fourfront/pull/1244
> Server Defaults Fix

- src/encoded/tests/data/inserts/variant_consequence.json
Added test inserts for 2 variant_consequence items.
> Added test inserts for variant_consequence items

- src/encoded/schemas/sample.json
- src/encoded/tests/data/master-inserts/user.json
This is a small PR with only a few edits, mainly so that my user insert gets in sooner. More edits to schema and types files are coming.
- added a few fields to sample schema
- made reference_protocol field in sample schema a Document linkTo
- added user to master-inserts
> Sample edits

- src/encoded/search.py
- Port https://github.com/4dn-dcic/fourfront/pull/1264
> C4-49 small performance fix

- src/encoded/schemas/individual.json
- src/encoded/schemas/sample.json
- src/encoded/tests/data/inserts/individual.json
- src/encoded/tests/data/inserts/sample.json
- src/encoded/tests/test_types_sample.py
- src/encoded/types/sample.py
**Summary**
- more Sample fields added or rearranged
- "label" parameter on property added, to indicate whether prop refers to specimen, requisition, or test
- other_specimen_ids, other_sequence_ids, and library_info added as SEOAs
- lookup numbers added to Sample
- lookup numbers added to Individual
Question: should institution, project be required for Individual?
> Sample edits 3

- package-lock.json
- package.json
- src/encoded/static/components/item-pages/CohortView/CohortSubmissionView.js
Testing Notes: 
- Must be tested along with [this branch](https://github.com/4dn-dcic/shared-portal-components/pull/25) on SPC; otherwise cohort submission page is going to crash.
Changelog:
- Swapped arguments in `<PanelOne>`'s `handleSelectInstitution()` & `handleSelectProject()` methods to accommodate changes made in [this PR](https://github.com/4dn-dcic/shared-portal-components/pull/25) (and for reasons further described there).
- Pass `searchAsYouType = true` prop into `<LinkToFieldSection>` in `<PanelOne>` render method (forces `<LinkToDropdown>` to display with SAYT functionality).
Todo:
> Saytajax for cohort view

- pyproject.toml
- src/encoded/schemas/variant_consequence.json
Add two properties to variant consequence item to support summarized consequence facets.
> Var cons upd

- deploy/tests/test_generate_production_ini.py
This fixes a problem where unit tests did not run locally.
> Fix deployment unit tests, which didn't run locally.

- pyproject.toml
- src/encoded/schemas/individual.json
`related_documents` field (array of linkTo:Document) added to individual to allow upload of related files - clinical notes, test results, etc.
> Individual documents

- poetry.lock
- pyproject.toml
This includes dcicutils 0.23.0 to support automatic index_server support.
> Automatic index_server support

- pyproject.toml
- src/encoded/tests/test_schemas.py
Added tests for pattern regex on gene fields to test_schemas.py.
> Pattern tests

- poetry.lock
- pyproject.toml
- src/encoded/tests/test_auth0.py
The intent of this is to accept `snovault 3.0.3` with the tentative fix to the purge sleep problem. Along the way, I had to disable a couple of tests. The ticket [C4-173](https://hms-dbmi.atlassian.net/browse/C4-173) will remind us to fix things.
> Accept snovault 3.0.3

- pyproject.toml
- src/encoded/tests/data/master-inserts/user.json
Installing me as a CGAP user (ran into this after a test failure)
Generated a new uuid with:
```
import uuid
uuid.uuid4()
```
> Adding user creds for tests, Eric Berg

- pyproject.toml
- src/encoded/tests/data/inserts/filter_set.json
This fixes [C4-197](https://hms-dbmi.atlassian.net/browse/C4-197).
> Fix problem in deploy1 in cgap-portal 2.1.0 (C4-197)

- Makefile
- pyproject.toml
- scripts/kibana-start
- scripts/kibana-stop
Adds support for `make kibana-start` and `make kibana-stop` in the local dev environment.
> Add ability to start/stop local kibana

- .travis.yml
- Makefile
- pyproject.toml
- Updates ES cluster configuration for testing to use the cgap-testing cluster
> Use cgap-testing for builds

- src/encoded/static/components/item-pages/CaseView/CaseStats.js
- src/encoded/static/components/item-pages/CaseView/index.js
Small edits requested by Burak and detailed here: https://trello.com/c/EwPrEYgh/163-case-progress-should-dictate-tabs
> Case tab improvements ui 1

- src/encoded/static/components/item-pages/VariantSampleView/GeneTabBody.js
- src/encoded/static/components/item-pages/VariantSampleView/SampleTabBody.js
- src/encoded/static/components/item-pages/VariantSampleView/VariantSampleInfoHeader.js
- src/encoded/static/components/item-pages/VariantSampleView/VariantTabBody.js
Fix for missing genotype_label errors, prepare for switch from genotype_label.role identifier to genotype_label.sample_id identifier.
> Annotation Space 2

- package-lock.json
- package.json
- pyproject.toml
- src/encoded/tests/data/demo_inserts/higlass_view_config.json
- src/encoded/tests/data/master-inserts/higlass_view_config.json
Update higlass-orthologs dependency
> Update higlass-orthologs dependency

- pyproject.toml
- src/encoded/submit.py
- src/encoded/tests/test_submit.py
**In this PR**
Submission related changes:
- "full brother", "full sister", "full sibling" now allowed as relation to proband, in addition to "sister", "brother", and "sibling"
- in relation to proband, sibling relations can have numbers append (e.g. "full brother 2")
- logic for determining whether report is required is connected to Case, not Sample (ie., now if a sample is part of 2 analyses, it is possible for one case to have a report and the other case not).
- unit tests and fixtures updated to cover these new situations.
- If ID values have spaces, these will be replaced with an underscore.
> Minor submit edits

- .ebextensions/20_packages.config
- pyproject.toml
- Ports https://github.com/4dn-dcic/fourfront/pull/1399
> Pin Poetry Version

- pyproject.toml
- src/encoded/tests/test_util.py
- src/encoded/types/file.py
- src/encoded/util.py
- Raise HTTPForbidden if a file download is attempted while not logged in.
> C4-356 Disable unauthenticated downloads

- poetry.lock
- pyproject.toml
Require dcicsnovault ^4.0.11 and dcicutils ^1.3.1.
> Accept dcicutils 1.3.1 (C4-361)

- pyproject.toml
- src/encoded/schemas/user.json
'user_institution' property added to User schema
- denotes the institution a user belongs to (rather than the institution that dictates who can view the User item) 
- will be used by submitCGAP to decide what institution should be assigned to items that a user submits
Comments welcome about whether prop should be an array rather than single item linkTo
> User institution

- pyproject.toml
- src/encoded/schemas/mixins.json
- src/encoded/schemas/user.json
- src/encoded/tests/data/inserts/gene.json
- src/encoded/tests/data/inserts/gene_list.json
- src/encoded/tests/data/workbook-inserts/file_format.json
- src/encoded/tests/datafixtures.py
- src/encoded/tests/test_batch_download.py
- src/encoded/tests/test_parse_hpoa.py
- src/encoded/tests/test_post_put_patch.py
- src/encoded/tests/test_types_init_collections.py
Small PR to remove the retired 'role' property from user schema and the 3 old statuses from the status enum.
> Perm rm ret props stati

- pyproject.toml
- src/encoded/static/components/navigation/components/AccountNav.js
- Allows people to login to CGAP using Google, see image below
> C4-386 Allow Google Login

- pyproject.toml
- src/encoded/tests/data/master-inserts/user.json
`user_institution` property was added to some of the inserts in src/encoded/tests/data/master-inserts/user.json.
> User institution inserts

- src/encoded/static/components/item-pages/CaseView/CurrentFamilyController.js
- src/encoded/static/components/item-pages/CaseView/PedigreeTabView.js
- src/encoded/static/components/item-pages/CaseView/PedigreeTabViewBody.js
- src/encoded/static/components/item-pages/CaseView/index.js
- src/encoded/static/components/item-pages/components/PedigreeDetailPane/index.js
- src/encoded/static/components/viz/PedigreeViz/data-utilities.js
- src/encoded/static/components/viz/PedigreeViz/index.js
- src/encoded/static/components/viz/PedigreeViz/layout-utilities-ordering-deprecated.js
- src/encoded/static/components/viz/PedigreeViz/layout-utilities.js
- webpack.config.js
This PR continues on PR https://github.com/dbmi-bgm/cgap-portal/pull/268 to also split out the PedigreeViz into a separate bundle (will change this PR to point to master once `code-split-edits` is merged).
New 'pedigree-viz.js' bundle (purple outline) + thoughts on what to code-split into sep. bundle in future (red outline).
~~Might split out react-workflow-viz in this branch later, actually..~~ Later.
> Code-Split-Out PedigreeViz into sep. JS bundle

- package-lock.json
- package.json
- pyproject.toml
- src/encoded/search/compound_search.py
- src/encoded/search/lucene_builder.py
- src/encoded/search/search.py
- src/encoded/search/search_utils.py
- src/encoded/static/components/navigation/components/CollapsedNav.js
- src/encoded/static/components/static-pages/HomePage/UserDashboard.js
- src/encoded/static/scss/encoded/modules/_forms.scss
- Remove 'from' and 'limit' from filters.remove URL
- Preserve generator for self.return_generator
- Preserve `@graph` list for other conditions
> Minor Search Edits

- src/encoded/static/components/browse/CaseDetailPane.js
- src/encoded/static/scss/encoded/modules/_tables.scss
Removal of some (deprecated) 4DN-specific CSS. Part of this can be migrated back in from 4DN if we introduce file download to CGAP portal in future.
> Minor CSS - Label alignment in Case detail pane..

- src/encoded/static/components/item-pages/CaseView/PedigreeTabView.js
- src/encoded/static/components/item-pages/CaseView/PedigreeTabViewBody.js
- src/encoded/static/components/item-pages/CaseView/index.js
- src/encoded/static/components/item-pages/UserView.js
- src/encoded/static/components/item-pages/components/PedigreeDetailPane/DiseasesLegend.js
- src/encoded/static/components/item-pages/components/PedigreeDetailPane/Files.js
- src/encoded/static/components/item-pages/components/PedigreeDetailPane/IndividualBody.js
- src/encoded/static/components/item-pages/components/PedigreeDetailPane/index.js
- src/encoded/static/components/navigation/components/AccountNav.js
- src/encoded/static/components/navigation/components/LoginNavItem.js
- src/encoded/static/components/viz/PedigreeViz/IndividualNodeShapeLayer.js
- src/encoded/static/components/viz/PedigreeViz/default-props.js
- src/encoded/static/components/viz/PedigreeViz/index.js
- src/encoded/static/scss/encoded/modules/_common-visualization-detail-pane.scss
- src/encoded/static/scss/encoded/modules/_item-pages.scss
- src/encoded/static/scss/encoded/modules/_pedigree-visualization-detail-pane.scss
- src/encoded/static/scss/encoded/modules/_pedigree-visualization.scss
- src/encoded/static/scss/encoded/modules/_workflow-visualization.scss
Should look like the following, and work as expected (UX-wise).
Functionality is same as when this Legend was in dropdown, but now, the color per phenotypic feature (or 'disease', in code-variable terms) is preserved and doesn't change if change a different color.
This resulted in a tiny bit of cleanup as well, since now `diseaseToIndex` (== `visibleDiseaseIdxMap`) is always an object and not an array so code to transform between the 2 data structures in this particular case is no longer needed.
> Pedigree DetailPane Legend

- src/encoded/static/components/item-pages/VariantSampleView/VariantSampleInfoHeader.js
- src/encoded/static/components/item-pages/VariantSampleView/VariantTabBody.js
Small replacement updates for:
- polyphen score
- hg19
- gerp
- sift
> V20 UI updates 2

- src/encoded/ingestion/table_utils.py
- src/encoded/schemas/variant_sample.json
- src/encoded/static/components/browse/columnExtensionMap.js
- src/encoded/static/components/item-pages/CaseView/FilteringTab.js
- src/encoded/static/components/item-pages/VariantSampleView/VariantSampleInfoHeader.js
- src/encoded/static/components/item-pages/VariantSampleView/VariantSampleOverview.js
- src/encoded/static/components/item-pages/VariantSampleView/VariantTabBody.js
Self-explanatory -- changes SearchResultTable VariantSample to look bit more like was before.
> UI edits re: VCF updates -- SearchResultTableColumns

- pyproject.toml
- src/encoded/ingestion/variant_utils.py
- src/encoded/ingestion/vcf_utils.py
- src/encoded/tests/test_vcf_utils.py
- Adjusts the ingestion behavior to also attempt patch on `variant_sample`
- Fixes `comhet_transcript` parsing
> Post/Patch Variant Sample

- pyproject.toml
- src/encoded/annotations/variant_table_v0.5.2.csv
- src/encoded/ingestion_listener.py
- src/encoded/schemas/variant_sample.json
- src/encoded/search/lucene_builder.py
- src/encoded/tests/test_variant_table_intake.py
- Augments our `terms` aggregations to `include` fields requested in the search (so counts are always available)
- Update DP column order `20` -> `40`
- Fix Ingestion Error reporting
> C4-103 Include Terms Agg

- pyproject.toml
- src/encoded/annotations/variant_table_v0.5.2.csv
- src/encoded/ingestion_listener.py
- src/encoded/schemas/variant_sample.json
- src/encoded/search/lucene_builder.py
- src/encoded/tests/test_variant_table_intake.py
- Reverts dbmi-bgm/cgap-portal#324
- Can't be implemented the way I did it since `include` is a hard filter.
> Revert "C4-103 Include Terms Agg"

- pyproject.toml
- src/encoded/tests/test_types_variant_sample.py
- src/encoded/types/variant.py
Bamsnap path change `<accession>/bamsnap/chr1:1234.png` to `<accession>/bamsnap/chr1_1234.png`
> Bamsnap path

- pyproject.toml
- src/encoded/commands/create_mapping_on_deploy.py
- src/encoded/ingestion_listener.py
- src/encoded/tests/test_create_mapping.py
- Repair error reporting to use the correct `IngestionReport`
> Fix Listener Error Reporting

- Makefile
- pyproject.toml
- src/encoded/ingestion/variant_utils.py
- src/encoded/tests/test_types_variant_sample.py
- src/encoded/types/variant.py
- Grab variant uuid from post/patch response
- Correctly resolve variant_sample patch URL via annotation_id
> C4-620 Fix VS Patch

- src/encoded/static/components/app.js
- src/encoded/static/components/browse/variantSampleColumnExtensionMap.js
- src/encoded/static/components/item-pages/CaseView/InterpretationTab.js
- src/encoded/static/components/item-pages/CaseView/index.js
- src/encoded/static/components/item-pages/VariantSampleView/InterpretationSpaceController.js
- src/encoded/static/components/item-pages/VariantSampleView/VariantSampleOverview.js
- src/encoded/static/scss/encoded/modules/_item-pages.scss
edits with custom modal (a separate branch because I wasn't sure if I would be able to complete it in time and wanted to be able to easily revert back to the browser alert version without losing changes)
> Interpretation space UI wcustommodal

- src/encoded/static/components/item-pages/VariantSampleView/VariantTabBody.js
Associated Ticket: https://trello.com/c/ORczmYsI/332-cadd-score-display
Notes:
Was going to add that bioinfo ticket to this branch too, but decided to throw it back on the backlog, since I don't have enough information to complete it ATM.
> move CADD to conservation predictors

- deploy/post_deploy_testing/cypress/integration/04a_search_views_local.js
- deploy/post_deploy_testing/cypress/integration/05a_case_view_basic.js
- deploy/post_deploy_testing/cypress/integration/05b_case_view_fsui.js
- deploy/post_deploy_testing/cypress/support/commands.js
- src/encoded/tests/data/master-inserts/user.json
Tests some basic aspects of CaseView.
We should create more files to test things like submission -- but have plan for what to do with created items (delete them after, perhaps).
I'll try to push a few more slightly more complex tests that deal w. creating/deleting things to this branch before merging.
[Video - testing against prod from local machine](https://gyazo.com/a107dde16d36c2aed6baf8ca79578546)
[Github Action Run](https://github.com/dbmi-bgm/cgap-portal/actions/runs/812254154)
> Cypress Tests (basic, pt. 2)

- src/encoded/static/components/item-pages/VariantSampleView/VariantSampleInfoHeader.js
- src/encoded/static/components/item-pages/VariantSampleView/VariantTabBody.js
- src/encoded/static/scss/encoded/modules/_item-pages.scss
Using stale data on local, should look like [this](https://gyazo.com/ec48c4059ff949fd27105f72c1468308).
Will be deployed to cgapwolf likely soon.
> GnomAD v2 table

- src/encoded/static/components/item-pages/CaseView/InterpretationTab.js
- src/encoded/static/components/item-pages/CaseView/index.js
Also adds loading icon to its body.
> Keep InterpretationTab un-disabled if VSL is loading

- src/encoded/schemas/variant_sample.json
- src/encoded/static/browser.js
- src/encoded/static/components/app.js
- src/encoded/static/components/item-pages/VariantSampleView/ExternalDatabasesSection.js
- src/encoded/static/components/item-pages/VariantSampleView/VariantTabBody.js
- src/encoded/static/components/viz/PedigreeViz/IndividualsLayer.js
- src/encoded/static/scss/encoded/modules/_item-pages.scss
- src/encoded/static/scss/encoded/modules/_pedigree-visualization.scss
Still ongoing, changes so far:
2021-06-14 & earlier
- Add+Update Facets
- Remove Clinvar Submission List/#
- PedigreeViz bullet point iteration
2021-06-15
- UCSC ext link
- \+ Clinvar ext link style iteration
- gnomAD ext link
> June demo feedback-related edits

- src/encoded/schemas/variant_sample.json
- src/encoded/static/components/item-pages/VariantSampleView/VariantTabBody.js
> GnomAD v2 External Link

- package-lock.json
- package.json
- pyproject.toml
- src/encoded/nginx-dev.conf
- src/encoded/static/components/item-pages/components/PedigreeDetailPane/Files.js
Requires this SPC PR: https://github.com/4dn-dcic/shared-portal-components/pull/75
> Pedigree upload checkbox

- src/encoded/authentication.py
- src/encoded/static/components/app.js
- webpack.config.js
- [Content Security Policy on MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP)
> Minor Security Edits

- pyproject.toml
- src/encoded/authentication.py
- Secret is no longer b64 encoded, so do not decode
> Repair Auth0

- poetry.lock
- pyproject.toml
- Updates `waitress` major version to close security issue
> Waitress Update

- pyproject.toml
- src/encoded/tests/test_types_case.py
- src/encoded/types/case.py
Create new calc prop on case for identifying structural variant samples associated with the case's SV VCF.
> SV Filter Addon

- pyproject.toml
- src/encoded/schemas/case.json
- src/encoded/schemas/individual.json
- src/encoded/schemas/sample.json
"Gender" facet title renamed to "Sex"
"Specimen Accession" prop title renamed to "Specimen ID" (this doesn't change the display of the accessioning table, however - needs to be fixed in front end code)
> Misc prop titles

- Makefile
- pyproject.toml
- src/encoded/__init__.py
- Do not blow away Auth0 settings if present
> Fix __init__

- package-lock.json
- package.json
- pyproject.toml
- src/encoded/static/components/item-pages/components/HiGlass/HiGlassPlainContainer.js
- src/encoded/static/components/item-pages/components/HiGlass/higlass-dependencies.js
- src/encoded/tests/data/inserts/higlass_view_config.json
This will allow to display of a chromosome band track in the SV browser
> Add higlass-general-vcf dependency

- .dockerignore
- docs/public/help/logging_in.md
- pyproject.toml
- Updates the existing login documentation with some more detailed information
> Login Documentation

- pyproject.toml
- src/encoded/static/components/item-pages/CaseView/index.js
See [this Trello Ticket](https://trello.com/c/twDy9eAV/447-ui-update-for-new-sv-quality-metric-summaries) for details.
~~Could use additional testing and feedback, since I wrote this without any actual backing data to test with.~~ Was able to test by pulling down [this case](http://fourfront-cgapwolf.9wzadzju3p.us-east-1.elasticbeanstalk.com/cases/GAPCAPRHOS27/) from cgapwolf.
**Screenshot from local test:**
[![Image from Gyazo](https://i.gyazo.com/aaab60895ccfa046f3598af89592dc17.png)](https://gyazo.com/aaab60895ccfa046f3598af89592dc17)
> Sv qc summary UI fix

- pyproject.toml
- src/encoded/root.py
Fix for the foursight-cgap url that appears on the health page.
> Foursight url fix

- deploy/docker/production/nginx.conf
- pyproject.toml
- src/encoded/types/case.py
- src/encoded/types/meta_workflow.py
Embeds desired for clone case foursight check
Case:
- meta_workflow_run.meta_workflow.name
- meta_workflow_run.meta_workflow.version
> Mwfr embeds

- pyproject.toml
- src/encoded/schemas/meta_workflow_run.json
We want to compute the total cost of a meta workflow run when it is complete. This PR adds `cost` to the schema.
> Add cost to MetaWorkflowRun schema

- package-lock.json
- package.json
- pyproject.toml
Fixes an issue where the Higlass sequence track would only show black rectangles on certain systems.
> Bump higlass-sequence version

- pyproject.toml
- src/encoded/static/components/item-pages/VariantSampleView/VariantSampleOverview.js
Unbreaking variant sample overview page. Whoops.
> Vso hotfix

- package-lock.json
- package.json
- pyproject.toml
- src/encoded/static/components/app.js
- src/encoded/static/components/static-pages/HomePage/UserDashboard.js
- src/encoded/static/scss/encoded/modules/_forms.scss
- src/encoded/static/scss/encoded/modules/_navbar.scss
- webpack.config.js
**[See Video](https://gyazo.com/4b3ee782d5874b8423449a933509cd04)**
Might add more clear "search" (and "clear") button in future but this should be decent enough I think.. most people have an "Enter" key on keyboard or "Submit" button on their mobile/tablet touch device's virtual keyboard...
Current 'issue' is that sometimes don't get expected search results, e.g. "S1-C1" returns No Results. But works decently otherwise.
Might play with padding/styling slightly before merging but otherwise ready for review.
---
Also contains a few unrelated changes, namely **(a)** explicitly adding "url" to package.json which we use already and has been installed as sub-dependency (can verify it's the node_modules/url installation being used in Chrome DevTools). See [related …
> User Dashboard (Homepage) Search

- pyproject.toml
- src/encoded/search/compound_search.py
- src/encoded/static/components/browse/variantSampleColumnExtensionMap.js
- src/encoded/static/components/item-pages/CaseView/CaseViewEmbeddedVariantSampleSearchTable.js
> Compound Search: Identify matched filter blocks

- src/encoded/schemas/variant_sample_list.json
- src/encoded/static/components/item-pages/CaseView/FilteringTableFilterSetUI/AddToVariantSampleListButton.js
- src/encoded/static/components/item-pages/CaseView/InterpretationTab.js
- src/encoded/static/components/item-pages/CaseView/VariantSampleListController.js
- src/encoded/static/components/item-pages/CaseView/VariantSampleSelection.js
- src/encoded/static/components/item-pages/CaseView/index.js
- src/encoded/tests/test_types_variant_sample.py
- src/encoded/types/structural_variant.py
- src/encoded/types/variant.py
From "structual_variant_sample_item" to "variant_sample_item".
> Update VSL SV field name

- docs/public/help/accessioning_3.md
- docs/public/help/family_history_3.md
- docs/public/help/logging_in.md
- pyproject.toml
In this PR:
- support email address changed in md docs
- readthedocs link added for SubmitCGAP documentation
- a little extra detail added in md files concerning CLI submission of cases and family history
> More submit docs

- pyproject.toml
- src/encoded/appdefs.py
- src/encoded/commands/create_mapping_on_deploy.py
- src/encoded/root.py
- src/encoded/tests/test_root.py
* Implements new /type-metadata endpoint to get the indexing order data.
> Add /type-metadata for order

- src/encoded/static/components/item-pages/VariantSampleView/AnnotationSections.js
- src/encoded/types/variant.py
Adds outbound link to search clinvar for variants at same location as currently-viewed VS/variant.
> ClinVar Search External Link

- CONTRIBUTING.rst
- pyproject.toml
This change adds a start at a contribution policy and a code of conduct that can fill the gap until Bianca's
fuller version is in place.
> Add a CONTRIBUTING.rst

- pyproject.toml
- src/encoded/schemas/file.json
- src/encoded/schemas/project.json
- src/encoded/types/base.py
The schemas changes required for this PR: https://github.com/dbmi-bgm/foursight-cgap/pull/79
> Schema changes for lifecycle management

- CHANGELOG.rst
- poetry.lock
- pyproject.toml
- src/encoded/tests/conftest_settings.py
- src/encoded/tests/test_ingestion_metadata_bundle.py
- src/encoded/tests/test_misc.py
* Add CHANGELOG.rst
* Add testing for consistent version and changelog.
* PEP8 adjustment in `src/encoded/tests/test_ingestion_metadata_bundle.py`
> Add CHANGELOG.rst

- CHANGELOG.rst
- Dockerfile
- Makefile
- pyproject.toml
Until we're more confident poetry 1.2.0 is stable, since it seems an incompatible change, this pins poetry 1.1.15.
* Change Dockerfile
* Change Makefile
> Pin poetry 1.1.15

- CHANGELOG.rst
- docs/public/help/accessioning_1.md
- docs/public/help/accessioning_4.md
- docs/public/help/family_history_1.md
- docs/public/help/family_history_4.md
- docs/public/help/file_uploads_1.md
- docs/public/help/file_uploads_2.md
- docs/public/help/genelist.md
- docs/public/help/tutorials_1.html
- docs/public/help/tutorials_2.html
- docs/public/help/video_tutorials.md
- pyproject.toml
- src/encoded/tests/data/master-inserts/page.json
- src/encoded/tests/data/master-inserts/static_section.json
accessioning, gene list, file upload, and family history. Included some changes to master inserts.
> Embedded Youtube videos as new section in several statis help pages:

- CHANGELOG.rst
- pyproject.toml
- src/encoded/static/components/static-pages/HomePage/GuestHomeView.js
Updating now-broken video tutorials link on portal sign-in page
> fix video tutorial link

- CHANGELOG.rst
- pyproject.toml
- src/encoded/__init__.py
- Repairs startup error seen on local deploy
> Fix local deploy

- CHANGELOG.rst
- docs/source/index.rst
- docs/source/infra_landing.rst
- pyproject.toml
- Updates readthedocs to include some info on the infrastructure repository
> Add Infra Landing Page

- CHANGELOG.rst
- pyproject.toml
- src/encoded/submit.py
- src/encoded/tests/test_submit.py
Here, we update the submission code to make all submitted files have a lifecycle policy, currently set to store files in infrequent access.
> Submitted File Lifecycle Policy

- CHANGELOG.rst
- package-lock.json
- package.json
- pyproject.toml
- src/encoded/static/components/app.js
- src/encoded/visualization.py
- Bump cohort browser
- Add `blob:` to `script-src` CSP
- Switch to presigned links everywhere
> Cohort browser updates

- CHANGELOG.rst
- Dockerfile
- deploy/docker/production/install_nginx.sh
- pyproject.toml
- Updates GPG key configuration/import for nginx so `docker build` can complete
> Repair Docker Build

- CHANGELOG.rst
- package-lock.json
- package.json
- pyproject.toml
- src/encoded/visualization.py
Fixes bug when no `variantDetailSource` is specified int the `CohortBrowser` component
> Bump cohort browser

- CHANGELOG.rst
- pyproject.toml
- src/encoded/tests/data/__init__.py
- src/encoded/tests/data/master-inserts/user.json
Here, we remove Dana's user from master inserts.
> Remove Dana user insert

- CHANGELOG.rst
- package-lock.json
- package.json
- pyproject.toml
**Changelog:**
- Ran `npm audit` and `npm audit fix`
- Went through list of open Dependabot PRs and merged the ones that didn't break anything or require reverting to a previous version
- Bump to latest version of SPC (v.0.1.76) - also changed method of install (when updating SPC, do `npm install github:4dn-dcic/shared-portal-components#v.v.v` from now on; this should make `package-lock` bugs less likely)
**Dependabot PRs Tested:**
**Notes:**
- Crypto JS fix (last remaining criticals) made in `shared-portal-components`
> Bm feb2024 npm updates
