dbmi-bgm/cgap-portal

src/encoded/__init__.py, src/encoded/root.py, src/encoded/tests/conftest.py, src/encoded/tests/test_views.py
- Add `indexer.namespace` option to the health page under `namespace`
- Change `mirror.env.es` to `mirror.env.name`, since now we can acquire the ES endpoint and the namespace from the health page
=> Health page

src/encoded/static/components/item-pages/CohortView/CohortSummaryTable.js, src/encoded/types/cohort.py
Columns updated to take advantage of new schemas:
- workup_type
- specimen_notes (w/specimen_collection_date)
- completed_processes (processing type is just the first item in this array)
Pretty light changes for demo. Wanted to add a fixed-width to the Individual column to keep them aligned regardless of current family selection... haven't gotten around to it.
=> Add missing data to cohort table; remove variant column

src/encoded/schemas/sample.json
CRAM file field added on samples, this is an alternative file format
(processed) that can be submitted instead of fastq files.
=> CRAM files

buildout.cfg, src/encoded/dev_servers.py, src/encoded/root.py, src/encoded/tests/data/README.md, src/encoded/tests/test_aggregation.py, src/encoded/tests/test_batch_download.py, src/encoded/tests/test_indexing.py, src/encoded/tests/test_post_put_patch.py, src/encoded/tests/test_search.py, src/encoded/tests/test_static_page.py, src/encoded/tests/test_types_init_collections.py, src/encoded/tests/test_validation_errors.py, src/encoded/tests/testing_views.py, src/encoded/tests/workbook_fixtures.py
**DO NOT FORGET TO UPDATE SNOVAULT BRANCH IN BUILDOUT.CFG**
This branch is the CGAP complement to https://github.com/4dn-dcic/snovault/pull/111. It adds some functionality specific to the new Elasticsearch items and a few other misc things.
**Summary**
- dev_servers.py changed to run `create_mapping` before and after loading test data. This is done to initialize any ES-item indices before loading, as well as deduplicate the queue before serving the application (and thus indexing)
- `/counts` refactored a bit. May be slightly less performant, but is now much more maintainable
- Refactored some indexing-related test features. This previously in `.features.conftest` have been moved to `workbook_fixtures`
- Removed last reference to `linkFrom` in the testing types
- Other random test fix
=> Es item -- CGAP. NOT READY

src/encoded/commands/clear_db_es_contents.py, src/encoded/commands/generate_items_from_owl.py, src/encoded/commands/load_data.py, src/encoded/commands/parse_hpoa.py, src/encoded/commands/verify_item.py, src/encoded/loadxl.py, src/encoded/tests/conftest.py, src/encoded/tests/test_access_key.py, src/encoded/tests/test_auth0.py, src/encoded/tests/test_authentication.py, src/encoded/tests/test_clear_es_db_contents.py, src/encoded/tests/test_create_mapping.py, src/encoded/tests/test_edw_hash.py, src/encoded/tests/test_embedding.py, src/encoded/tests/test_indexing.py, src/encoded/tests/test_load_access_key.py, src/encoded/tests/test_loadxl.py, src/encoded/tests/test_owltools.py, src/encoded/tests/test_permissions.py, src/encoded/tests/test_search.py, src/encoded/tests/test_server_defaults.py, src/encoded/tests/test_types_file.py, src/encoded/tests/test_types_init_collections.py, src/encoded/tests/test_types_tracking_item.py, src/encoded/tests/workbook_fixtures.py, src/encoded/types/base.py, src/encoded/types/file.py, src/encoded/types/page.py, src/encoded/verifier.py
This changes absolute references to the repo (which calls itself 'encoded') into relative references.
=> Use relative imports for encoded

src/encoded/types/__init__.py
Problem: currently can't upload any pedigrees, problem due to mimetype mismatch issue
In this PR:
- overrides mimetypes_are_equal method in Document class (inherited from ItemWithAttachment class in snovault) to avoid pbxml problems (avoids changes in snovault)
[Note: building locally won't work without "fix inserts" branch merged in]
=> mimetypes_are_equal override in class Document

src/encoded/commands/generate_items_from_owl.py, src/encoded/commands/load_items.py, src/encoded/commands/parse_hpoa.py, src/encoded/tests/data/documents/test_uberon4.owl, src/encoded/tests/data/documents/test_uberon5.owl, src/encoded/tests/test_generate_item_from_owl.py
1. Refactored main method of parse_hpoa.py to break it up a bit and make it easier to write tests.
2. Modified logging set up in all scripts that process Phenotype and Disease and Evidence items
3. Added tests for generate_items_from_owl.
=> Logging pde

src/encoded/types/cohort.py
**Problem:** Previous fix to cohort didn't fix inability to upload pedigree on cgap prod. Problem seemed to be duplicate (non-unique) items in family phenotypic_features list.
**In this PR:** One added line that only adds a phenotypic feature if it is not already present in list.
**Notes:**
- this wasn't apparent on local at first, because the error only seems to appear if the phenotypes are in the db as HPO terms.
- would be prudent to add a test for pbxml parsing - will work on this but would like to get this change in first so that pedigrees can again be uploaded on prod and other envs.
=> removed duplicates in phenotypic features processing

development.ini, pyproject.toml, src/encoded/static/components/item-pages/HealthView.js, test.ini
This fixes several visual things on the `/health` page:
* There's a label that said "Data Loaded" that I changed to "Loaded Data" because the order of presentation seems to be alphabetical order of the keys that can't be seen, so it helps to make the alphabetical order of the titles be consistent with the ordering of the keys.
* Added labeling for the project version and the beanstalk app version, which were recently added.
* Backfilled several other items that seem not to have entries and so were appearing without explanations and without pretty labels.
=> Tidying up of health page to use new version info, etc.

deploy/generate_production_ini.py, pyproject.toml
Per [C4-144](https://hms-dbmi.atlassian.net/browse/C4-144): There was an error in the deployment strategy we released recently for CGAP. It needs additional environment variables that won't be present in a default beanstalk so we shouldn't use the default deployment strategy involving `any.ini` in the init files. In this PR, we make the change conditional on a command line option that is defaultly `False`.
=> Fix premature release of the any.ini deployment strategy (C4-144)

src/encoded/search.py, src/encoded/tests/test_search.py
- When repairing nested facets, the original version blew away the boolean qualifiers.
- Reformats the query (into a sub-aggregation) to preserve the boolean qualifiers.
- Changes the `format_facets` code _slightly_ to account for new aggregation structure.
=> C4-143 Fix nested facets

pyproject.toml, src/encoded/commands/load_data.py, src/encoded/tests/test_loadxl.py
- `load_data` logic was never really configured for CGAP.
- This change will allow `load_data` to run on `cgaptest` on deployment while preventing it on other envs and allowing on local.
- This is done through the helper method `load_data_should_proceed`, which is tested in all (current) scenarios
=> C4-154 Load master-inserts on cgaptest

poetry.lock, pyproject.toml
This proposes to accept recent changes to snovault to remove dynamic imports.
If a new version of snovault is issued with a non-beta version, I'll update this PR to use that.
=> Accept version of snovault with dynamic imports removed

src/encoded/static/components/browse/columnExtensionMap.js
Bugfix for:
Transform error
ReferenceError: link is not defined
at renderFxn (/opt/python/bundle/2/app/src/encoded/static/build/webpack:/src/encoded/static/components/browse/columnExtensionMap.js:107:36)
at n.render (/opt/python/bundle/2/app/src/encoded/static/build/webpack:/node_modules/@hms-dbmi-bgm/shared-portal-components/es/components/browse/components/table-commons/ResultRowColumnBlockValue.js:183:31)
at d (/opt/python/bundle/2/app/src/encoded/static/build/webpack:/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:38:231)
at $a (/opt/python/bundle/2/app/src/encoded/static/build/webpack:/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:39:16)
at e.render (/opt/python/bundle/2/app/src/encoded/static/build/webpack:/node_modules/react-dom/cjs/react-dom- …
=> update workflow.title to use workflowHref or Link

Makefile, pyproject.toml
This adds support for doing `make psql-dev` to enter psql on the same connection parameters as `make deploy1` and `make deploy2` use, so that data being used to serve `localhost:8000` is inspectable.
=> Add support for 'make psql-dev'

.travis.yml, pyproject.toml, src/encoded/tests/test_indexing.py
Upgrade from Postgres 9.4 to Postgres 11 in Travis testing.
=> Use postgres 11 for travis testing

pyproject.toml, src/encoded/tests/data/inserts/sample.json
I was getting a conflict on `deploy1` because there are four data items in `src/encoded/tests/data/inserts/sample.json` that had `"bam_sample_id"` of `"test001_sample"`, `"test002_sample"`, `"test003_sample"`, and `"test003_sample"`. This fixes the fourth to be `"test004_sample"`, which I assume is what's needed. It makes the `deploy1` operation succeed on master.
=> Fix a duplicated bam_sample_id (C4-221)

poetry.lock, pyproject.toml
I did some poking at the `coveralls` error we've been getting in Travis builds for CGAP since last year ([C4-218](https://hms-dbmi.atlassian.net/browse/C4-218)), and it turns out that `coveralls` dropped support for any version of `coverage` below 5.0.  So I guessed that was the problem.  (Also, this is working in dcicutils, which is using version 5.1 of `coverage`, so that seemed to suggest a cure, too.)
Since `coverage` is a dev dependency and we don't really call it directly in any sophisticated way, I assume we can tolerate a major version upgrade, so I made that adjustment here. It seems to make coveralls work again. At least there is no reported error related to that in the Travis build transcript. It's broken on master [here](https://travis-ci.org/github/dbmi-bgm/cgap-portal/builds/ …
=> Upgrade coverage (C4-218)

.travis.yml, poetry.lock, pyproject.toml
This moves the dependency management for `coveralls`, `codacy-coverage`, and `coverage` into `pyproject.yaml`, so that we can get consistency checking for incompatible versions.
=> Move 'pip' depedencies for coveralls from .travis.yml to pyproject.toml

.travis.yml, Makefile, pyproject.toml
This small change has two effects:
* Use `make build` rather than a bunch of calls to lower-level things (`poetry install`, etc.) in `.travis.yml`, picking up `moto` in the process since it's done by `make build` and was not part of the lower level call sequence.
* Add `pip install --upgrade pip` to the list of things `make configure` does just because it's a good idea and might help some things install better. Travis was already doing this, but our install procedure documents you have to do it yourself if you want. Better not to leave it to chance.
=> Simplify travis build procedure more, picking up moto in the process

pyproject.toml, src/encoded/types/file.py
Address [C4-169](https://hms-dbmi.atlassian.net/browse/C4-169) as follows:
1. Make `FileProcessed` include `file_workflow_run_embeds_processed` **(fixes the bug)**.
2. Make `FileFastq` include `file_workflow_run_embeds` **(opportunistic - does this seem like a good idea?)**.
For reference, `file_workflow_run_embeds` implies:
```
'workflow_run_inputs.workflow.title',
'workflow_run_inputs.input_files.workflow_argument_name',
'workflow_run_inputs.input_files.value.filename',
'workflow_run_inputs.input_files.value.display_title',
'workflow_run_inputs.input_files.value.file_format',
'workflow_run_inputs.input_files.value.uuid',
'workflow_run_inputs.input_files.value.accession',
'workflow_run_inputs.output_files.workflow_argument_name',
'workflow_run_inputs.output_files.value.display_title', …
```
=> Address C4-169 workflow embed issue

pyproject.toml, src/encoded/ingestion_listener.py, src/encoded/search/lucene_builder.py, src/encoded/tests/data/variant_workbook/gene_workbook.json, src/encoded/tests/test_ingestion_listener.py, src/encoded/types/variant.py, src/encoded/types/workflow.py
- Fix/stub out issues Sentry pointed out from analyzing our testing that could be done quickly
- The biggest issue was in ingestion listener testing, which has been fixed by adding the relevant genes and denoting annotation_id as a name key on variant.
=> C4-252 Sentry Fixes

pyproject.toml, src/encoded/ingestion_listener.py, src/encoded/tests/test_ingestion_listener.py, src/encoded/tests/test_static_page.py
- Reduce flakiness of `test_ingestion_queue_add_and_receive` by forcing the test to receive in batches of size 1 and allowing retries on the receive.
=> C4-257 Reduce ingestion listener test flakiness

pyproject.toml, src/encoded/tests/test_util.py, src/encoded/types/cohort.py, src/encoded/types/family.py, src/encoded/util.py
There's a bit of code that's duplicated between `types/cohort.py` and `types/family.py` that I wanted to centralize so that I can maybe use it for other purposes.
Opportunistic:  The code for `generate_fastq_file` was not yet used and is now available via `dcicutils.data_utils.generate_sample_fastq_file`, so I removed it here. That makes the diffs of `utils.py` a little messy because I'm replacing one function with another when they are unrelated because it happens to be the same place in the file. Side-by-side diff will probably clear that up.
Adding @sbreiff  and @KorayKirli  as reviewers since this is code they've touched in the past. But I'm not really changing the functionality, just consolidating, so I don't expect this will upset anything.
=> Centralize some shared code related to finding email address of authorized user making a request

pyproject.toml, src/encoded/submit.py, src/encoded/tests/test_submit.py
Some output messages were changed to make them more intuitive for users. Sample new output:
```
file_fastq: 4 items created (with POST); 0 items failed creation
sample: 37 items created (with POST); 0 items failed creation
individual: 37 items created (with POST); 0 items failed creation
family: 11 items created (with POST); 0 items failed creation
sample_processing: 11 items created (with POST); 0 items failed creation
report: 11 items created (with POST); 0 items failed creation
case: 37 items created (with POST); 0 items failed creation
file_fastq: attributes of 4 items updated (with PATCH); 0 items failed updating
sample: attributes of 37 items updated (with PATCH); 0 items failed updating
individual: attributes of 37 items updated (with PATCH); 0 items failed updating
family: …
```
=> Submission post/patch result msgs

pyproject.toml, src/encoded/search/lucene_builder.py, src/encoded/search/search.py
This PR fixes two issues - the first problem is mapping resolution from the cache does not drill down far enough to correctly resolve nested paths, thus breaking nested searches. The second problem is in ES6 apparently you cannot compute a 'does not exist' query by wrapping the `MUST_NOT` sub-query in a `MUST` parent query. The following query used to work but now does not:
```
{
"query": {
"bool": {
"filter": [{
"bool": {
"must": [{
"nested": {
"path": "embedded.files",
"query": {
"bool": {
"must_not": [{
"exists": {
"field": "embedded.files.display_title.raw"
}
}]
}
}
}
}, {
"nested": {
"path": "embedded.cram_files",
"query": {
"bool": {
"must": {
"exists": {
"field": "embedded.cram_files.display_title.raw"
}
}
}
}
}
}]
...
```
To fix this, instead of wrapping the "must not exists" part …
=> Search fixes

pyproject.toml, src/encoded/search/search.py, src/encoded/search/search_utils.py, src/encoded/tests/data/sample_processing_mapping.json, src/encoded/tests/test_search.py
- `find_nested_path` returns the closest _top level_ nested field when we need the closest nested field to the source field. The former approximation works when you only search on top level nested fields, but fails when searching on sub-nested fields. 
- Augment the algorithm to keep track of all possible nested paths until it has drilled down as far as it can go - the last path seen is the closest in proximity to the nested field we are searching on.
- Add some tests to ensure the above is working.
=> C4-318 Fix nested searches on sub-nested fields

pyproject.toml, src/encoded/schemas/sample.json, src/encoded/tests/data/demo_inserts/sample.json, src/encoded/tests/data/inserts/sample.json, src/encoded/tests/test_submit.py, src/encoded/tests/test_types_sample.py
Suggested enum for `specimen_type` property in Sample schema changed from `["blood", "saliva"]` to 
`["peripheral blood", "cord blood", "plasma", "saliva"]`.
Inserts and tests edited accordingly.
=> Sample types

.ebextensions/20_packages.config, pyproject.toml
- On 10/1 a change was introduced to EB that triggered our setup_eb.py script to generate an extra directory and .pth file breaking the deployment
- Fix this by removing these files with `0698_remove_extra_files`
- Also pins pip and setuptools versions
=> C4-325 Fix deploy

.ebextensions/11_logs.config, pyproject.toml
This allows the custom logs deploy.log and custom_mappings.log to appear along with the default Beanstalk logs. It'll make debugging Beanstalk errors easier.
=> Bundle custom logs with beanstalk

pyproject.toml, src/encoded/ingestion_listener.py, src/encoded/schemas/file_processed.json
- Adds `In progress` to `file_ingestion_status`, patching in the ingester just before it downloads the processed file (ie: in current setup, a single processed file (at most) should be `In progress` when items are being generated from it)
- Adds `Error` to `file_ingestion_status`, patching in the ingester if an error occurred, otherwise `Ingested` status will be patched
- Add a log statement to debug intermediary PATCH on queueing, which doesn't seem to be working
=> Update ingestion statuses

pyproject.toml, src/encoded/ingestion_listener.py, src/encoded/schemas/file_processed.json, src/encoded/types/variant.py
- When an error occurs in ingestion, patch the error string to the associated FileProcessed
=> C4-352 Patch error info to FileProcessed

pyproject.toml, src/encoded/commands/ingest_genes.py, src/encoded/ingestion_listener.py
- Variants posted through the ingestion listener will now have status `shared`
- Genes ingested through the script will now have status `shared`
- NOTE: variants ingested directly through scripts will not have `shared` status
=> C4-320 Default variant/gene status to 'shared'

src/encoded/static/components/item-pages/VariantSampleView/SampleTabBody.js
Ok so apparently the location and coding_effect values I was looking for actually were coming in on variant when I pulled sample variant, and I didn't have to do a separate set of ajax request chains. Soooo all of that promisequeue stuff was basically scrapped. At least the bug in pedigree is fixed.
Currently, this component is making an ajax request each time it is mounted since the request is being done inside of the wrapper. Unfortunately this means switching between tabs results in a reload. Not sure what the best way around this is... I thought about moving a lot of the logic for the ajax request/some of the response handling higher up in the component hierarchy and caching it similarly to the way that gene is currently being cached. But I'm not sure how much sense it makes from an …
=> create wrapper component and do ajaxing

pyproject.toml, src/encoded/schemas/institution.json, src/encoded/schemas/project.json
There was a bug with project view permissions, where users couldn't view the project they were on when it was "current" and status couldn't be changed to "shared".
"shared" now allowed for project and institution status, and is the default status when they are created.
=> Project status

pyproject.toml, src/encoded/ingestion_listener.py
- Fixes 2 small issues with the Ingestion Listener
- First is incorrect function call args to `set_error`. Very unhappy that PyCharm did not catch that when this change went in, it had no problem highlighting it now.
- Second is upping visibility timeout of messages to 3 hours as it could reasonably take some time to ingest a VCF and we don't want to re-queue if we don't have to
=> Fix Small Ingestion Listener Bug

pyproject.toml, src/encoded/tests/data/master-inserts/institution.json, src/encoded/tests/data/master-inserts/project.json
Removed status property from project master inserts so that the default 'shared' will be used allowing view permission for logged in users.
Added MSA project and MSA institution to master inserts.
=> Upd status proj

src/encoded/static/components/app.js
Started having [issues with embedded search views](https://gyazo.com/28908ee252732a815e8245c68bdea559) after pulling in new master on CGAP. Traced it back to [this method](https://github.com/4dn-dcic/shared-portal-components/pull/50/files) in SPC.
```
Uncaught TypeError: Cannot read property 'apply' of null
at Function.navigate.updateUserInfo (navigate.js:97)
at onLoadResponse (VirtualHrefController.js:235)
at XMLHttpRequest.xhr.onreadystatechange (ajax.js:110)
```
Thanks to Utku for helping me figure out a better long-term solution to this bug
=> fix cannot read property 'apply' of null bug

pyproject.toml, src/encoded/ingestion_listener.py, src/encoded/schemas/file_processed.json, src/encoded/tests/test_ingestion_listener.py
- Updates the ingestion listener to provide more details when errors occur by patching the first 100 responses and associated rows to the `file_ingestion_error` field on `file_processed`.
- Sentry will now receive a (better) summary log message and verbose logging has been reduced.
- Some (very simple) unit tests on the error structure, which is very straightforward
=> C4-407 Ingestion Listener Error Reporting

pyproject.toml, scripts/kibana-start
Fixes the 'make kibana-start' bug for elasticsearch 6.8 (and bumps the patch version).
Tested manually by me and Will.
=> Fix kibana-start

pyproject.toml, src/encoded/authorization.py, src/encoded/search/lucene_builder.py, src/encoded/search/search.py, src/encoded/search/search_utils.py, src/encoded/tests/test_authorization.py, src/encoded/tests/test_search.py
- Addresses C4-501 by handling another possible query structure for nested aggregations
- Addresses C4-404 by adding an (admin only) search debug parameter. If `debug=<anything>` is passed to the search, the API will add the final query passed to ES to the response under the field `query` if the source user is an admin.
=> C4-501 C4-404 

src/encoded/static/components/item-pages/CaseView/PedigreeTabViewBody.js, src/encoded/static/components/item-pages/components/FullHeightCalculator.js, src/encoded/static/components/viz/PedigreeViz/data-utilities.js, src/encoded/static/scss/encoded/modules/_pedigree-visualization.scss
Minor code adjustments to prevent clientside UI error if ~~click on link for~~ load initial page at pedigree tab (CaseView, etc.)
---
Also adjusts BG color and sortByAge func so that proband is no longer the left-most child.
=> GlitchFix for #pedigree tab, sortByAge, bg color

package-lock.json, package.json, pyproject.toml, src/encoded/schemas/variant_sample.json
Test with [SPC branch](https://github.com/4dn-dcic/shared-portal-components/pull/54).
Update Strand Fisher Score to use range aggregation. 
- The score has a threshold of 20. `<=20` should be labelled "low strand bias" and `>20` "high strand bias" with description "Fisher P-value >= 0.01" and "Fisher P-value < 0.01", respectively. (Eventually, we may wish to add descriptions as tooltips, instead, but for now, I merged it into the label in schema).
Update Strand Fisher Score to use abbreviation.
- Added "abbreviation" for this field directly to `variantSample.json` schema facet definition... UI representation handled in SPC branch.
=> Range facet demo updates

src/encoded/static/components/browse/SearchView.js, src/encoded/static/components/item-pages/CaseView/index.js, src/encoded/static/scss/encoded/modules/_item-pages.scss, src/encoded/static/scss/encoded/modules/_search.scss
- Ensure height of the embedded FacetList header matches height of FacetList on /search/, which matches that of SearchResultTableHeader - [result](https://gyazo.com/9a9f3ad7b884f97fb68a1e76af92fce1)
- ~~Possible to-do: Have this height take effect in SPC or in same place as for SearchResultTableHeader, at least.~~
- Drawback of ^ is that then need to import search table scss and facetlist scss from SPC in order and that's arguably more headache of a requirement to need to remember and maintain than the way we sync height now..
- Use Bootstrap's `.card` in place of custom CSS when possible - [result](https://gyazo.com/9b910457b8e3fb66d7aa0186953bdf23)
- Remove/cleanup deprecated ActiveFiltersBar imports (superseded by FilterSetUI now)
=> Converge some CSS -

poetry.lock, pyproject.toml
This fixes [C4-563](https://hms-dbmi.atlassian.net/browse/C4-563), adding a proper lock file for the existing pyproject.toml.
=> Update poetry.lock after last PR 305 forgot it (C4-563)

Makefile, pyproject.toml, scripts/kibana-start, scripts/psql-start
This adds and repairs support for local kibana and psql debugging.
`make kibana-start` already existed as a way to start kibana on a local es on the default port used by `make deploy1`, though it had been broken. I fixed it.
`make kibana-start-test` now figures out what es is being used for active testing and will open kibana on that.
`make psql-dev` already existed to open psql on the postgres being used with `make deploy1`.
`make psql-test` is new and opens psql on the postgres used with `make test`.
The underlying script `scripts/kibana-start` is now more featureful. It takes an argument of a port or one of the constant tokens `test` or `dev` to have the port figured out automatically.
Likewise `scripts/psql-start` takes a port, `test`, or `dev`.
=> Support for local kibana and local psql (C4-566, C4-567)

pyproject.toml, src/encoded/ingestion/table_utils.py, src/encoded/renderers.py, src/encoded/tests/test_renderers.py, src/encoded/tests/test_variant_table_intake.py
Following up on [C4-571](https://hms-dbmi.atlassian.net/browse/C4-571) (and [cgap-portal PR #310](https://github.com/dbmi-bgm/cgap-portal/pull/310))
This sets application/json to be the preferred MIME type in the fall-through case of `should_transform` in `renderers.py`. I had a long chat with @alexkb0009 and @willronchetti about this and this seems to be the consensus. It's the value/behavior that was current at the start of January before my recent changes.
I have checked that this did not perturb SubmitCGAP on a localhost example of the file that @sbreiff gave me but she may want to check again.
In brief, the reason this came up is that I was writing some unit tests for this to cover recent changes and I discovered that none of us understood how the code was really working and that the …
=> Add renderers unit tests and revert to application/json default (C4-571)

src/encoded/static/components/item-pages/CaseView/FilteringTab.js
Ran into some client side errors when these values on gene came in null. Since it can break the entire search embed/view if a single item doesn't have these, made some slight adjustments.
=> prevent .split() null errors

Makefile, pyproject.toml, pytest.ini, src/encoded/tests/test_search.py
This fixes the spurious intermittent 404 described in [C4-570](https://hms-dbmi.atlassian.net/browse/C4-570).
This arranges to collect both the normal (non-deleted) _and_ deleted pages in order to do count checking. (This does not address the underlying issue that leads to deleted pages laying around.)
I added a regression test but I have marked that test with `@pytest.mark.manual`, a new tag that can be used to mark tests that will only be run if invoked manually. Our normal `make test` and `make travis-test` will now add `not manual` to the list of conditions about what to run.
The regression test does these things:
* It runs `test_index_data_workbook` normally, to show that it works in its intended way.
* It creates a deleted page and re-runs `test_index_data_workbook` to show that it …
=> Fix intermittent 404 in test_index_data_workbook (C4-570)

src/encoded/static/components/viz/PedigreeViz/data-utilities.js, src/encoded/static/components/viz/PedigreeViz/layout-utilities.js
Fixes issue with single-parent relationships having a child that also present in a multi-parent relationships with same parent.
Potentially relevant [text](https://github.com/dbmi-bgm/cgap-portal/pull/98) describing what's happening in this code overall.
=> PedigreeViz: Handle single-parent-relationships better

src/encoded/ingestion/table_utils.py, src/encoded/schemas/variant_sample.json, src/encoded/static/components/item-pages/VariantSampleView/SampleTabBody.js, src/encoded/static/components/item-pages/VariantSampleView/VariantSampleInfoHeader.js, src/encoded/static/components/item-pages/VariantSampleView/VariantTabBody.js
Changelog:
- fix for comphet coding effect + location error bug
- re-add `hg19`/data type fix (array => single value on variant)
- use variant.display_title as placeholder for  `hgvsg`
- fix sift score (`csq_sift` => `csq_sift_score`)
- fix spliceAI score (`spliceai_maxds` => `spliceaiMaxds`)
- make new range facets persistent via table utils (until Q2Q ingestion implemented -- lmk if this is correct phrasing/terminology)
- regenerate schemas with new range facets
- `csq_gnomad_af` duplicate => `csq_gnomadg_an`
Notes:
- Also updated Q2Q tab of VCF Mapping Table google doc with the new facet field names and some of the missing ones for future reference
- Alex mentioned it might make sense to remove `order` and `number_step` etc, so that those values are pulled from VCF table... but may not …
=> V20 UI updates 3

package-lock.json, package.json, pyproject.toml, src/encoded/static/components/forms/ExcelSubmissionView.js
**Changelog:**
- Open links to newly ingested items in new window by default (cgap excel submission interface, tab 2 post-success)
- Update SPC to `v0.1.2`, which updates multipart formdata ajax submission method for recent JWT updates
- Note: Popper.js core and aws-sdk auto-updated in `package.lock` on `npm install`
- Comment out some random `console.log()`s
=> Submit cgap fixes

pyproject.toml, src/encoded/submit.py, src/encoded/tests/test_submit.py
There was an issue where if an individual had multiple samples, represented as multiple lines on the submission spreadsheet, instead of individuals being linked to both samples, one sample would overwrite the other one. This has been fixed so that the 'samples' field on Individual gets extended, and multiple samples can be linked to an individual in submit.py.
=> Samples submit bug fix

src/encoded/static/components/item-pages/VariantSampleView/VariantTabBody.js
**Changelog:**
- Add support for Middle Eastern population data in gnomad table
- Add rankscores for the following: 
- `csq_sift`: `csq_sift_converted_rankscore`
- `csq_cadd_phred`: `csq_cadd_raw_rankscore`
- `csq_gerp_rs`: `csq_gerp_rs_rankscore`
- `csq_phylop100way_vertebrate`: `csq_phylop100way_vertebrate_rankscore`
- Add predictions for the following:
- `csq_sift` : `csq_sift_pred`
- `csq_polyphen2_hvar_score` : `csq_polyphen2_hvar_pred`
- `csq_primateai_score`: `csq_primateai_pred`
- Slight update to table styling now that there is more data, to make headings more clear/prominent
**Demos**
- Gnomad Table Updates:  https://gyazo.com/9e5556a7aaf21114d61c9c9225a17457
- Rankscores and Predictions: https://gyazo.com/a8c363a4e4ca63881a1c3537b00b05f2
**Testing Notes**
- At the time of …
=> V20 UI updates5

pyproject.toml, src/encoded/ingestion_listener.py
- Pass explicit encoding argument to file object read by `vcf.Reader`, which ignores standard encoding resolution rules.
=> Fix Ingestion Listener Encoding

src/encoded/authentication.py, src/encoded/renderers.py, src/encoded/tests/conftest.py
Has been tested on fourfront-cgaptest
Related to https://github.com/4dn-dcic/fourfront/pull/1486
For ordinary page requests from browser (non-AJAX), `request.referrer` is not present and hostname/`request_domain` is "None". When no explicit domain supplied upon ~~logout~~ session/token expiration (nor overwrite=True), the cookie is duplicated for sometimes-different domain (maybe prepends ".", making cookie applicable for subdomains of current domain) and doesn't log out user correctly.
On top of ensuring we passing in request.domain as cookie domain to overwrite/unset in renderer.py (primary edit), we also check now that request.referrer (or referer *) domain is present and matches request.domain for login requests (as an extra check, though not entirely necessary probably).
=> Proper domain when unset cookie re: expired session

src/encoded/static/components/item-pages/CaseView/FilteringTableFilterSetUI.js, src/encoded/types/variant.py
- Replaced `variant_samples.variant_sample_item.*` with more specific embeds for variant display titles and genotype labels
- Fix for broken add to selection button when `variantSampleList.variant_samples` is null/undefined
=> Pre may2021 demo embed fixes

pyproject.toml, src/encoded/schemas/note_discovery.json, src/encoded/schemas/note_interpretation.json, src/encoded/tests/data/workbook-inserts/note_interpretation.json, src/encoded/tests/test_types_note.py
In this PR:
- `gene_candidacy` enum in NoteDiscovery schema changed from Tier system to just strong, moderate, weak, not
- ACMG classification enum in NoteInterpretation schema changed to be capitalized
- relevant unit tests edited
=> Discovery enum change

pyproject.toml, src/encoded/static/components/forms/ExcelSubmissionView.js
Changelog:
- Re-added link to help documents to IngestionSubmission wizard. If "accessioning" was selected in the first panel, links to the accessioning doc. If "gene list", links to the gene list doc.
Notes: Since this is a really small PR and Alex is out for a few days, figure you two can approve it.
Short demo (sorry I have a billion tabs open/slow loading)
=> show submission help links

pyproject.toml, src/encoded/submit_genelist.py, src/encoded/tests/data/workbook-inserts/project.json, src/encoded/tests/data/workbook-inserts/variant_sample.json, src/encoded/tests/test_submit_genelist.py, src/encoded/tests/test_types_filter_set.py
During Wednesday's all-hands meeting, I noticed Joel submitted a gene list but a variant sample was not updated; in fact, many variant samples were being missed in the `variant_update` ingestion submission. After a good deal of digging, this turned out to be the result of an unknown, to me at least, limitation of VirtualApp GET requests with searches such that only 25 results are returned by default. 
This PR fixes the issue by paginating the `batch_search` method in chunks of 100 items until all items have been received.
Additionally, some light refactoring of the endpoint and the `genelist` ingestion submission was done to:
-  broaden the scope of the `batch_search` method so other search requests won't be limited to 25 items
-  queue variant samples in a project-specific manner to …
=> Fix variant_update endpoint's search limits

Makefile
Add a way to control ENV_NAME and AWS_ACCOUNT in docker commands of Makefile so that one can do something like:
```
make ENV_NAME="cgap-mastertest-foo" AWS_ACCOUNT="1234512345" build-docker-production
```
=> Add way to control ENV_NAME and AWS_ACCOUNT in Makefile docker commands

pyproject.toml, src/encoded/schemas/image.json
Update "Image" schema's title, description, and ID to appropriate values instead of matching those of the "Document" schema. This updates the "Data Type" facet for images when searching all items from "Document" to "Image".
=> Correct image schema metadata

pyproject.toml, src/encoded/docs/extended_description_VariantSample_inheritance_mode.html, src/encoded/docs/extended_description_VariantSample_inheritance_mode_probandonly.html, src/encoded/schemas/variant_sample.json, src/encoded/tests/test_types_case.py, src/encoded/tests/test_types_variant_sample.py, src/encoded/types/case.py, src/encoded/types/variant.py
Most of our current inheritance modes are designed for trio analyses. This PR introduces another inheritance mode facet that is designed for proband-only cases, when most inheritance modes can't be called due to lack of family members in the analysis. 
In this PR:
- new calc prop for proband_only_inheritance_modes
- inheritance_modes and proband_only_inheritance_modes now default_hidden in schema, and get unhidden by the additional_variant_sample_facets in case.py
- proband_only_inheritance_modes has its own tooltip from a new html doc, modeled after the one for inheritance_modes
=> Proband inheritance facet

pyproject.toml, src/encoded/schemas/case.json, src/encoded/schemas/family.json, src/encoded/schemas/mixins.json, src/encoded/submit.py, src/encoded/tests/data/demo_inserts/phenotype.json, src/encoded/tests/test_indexing.py, src/encoded/types/case.py
The main purpose of this PR is to put ingestion_ids on Family so that after a pedigree is submitted, a search table of the related Case(s) can be shown.
In this PR:
- ingestion_ids prop on Case moved to mixins
- ingestion_ids mixin added to Family
- Case now embeds individual.families.ingestion_ids
- submit.py edited to put ingestion_ids on family metadata
- phenotypes needed for submission of the test pedigree file have been added to demo_inserts
=> Family ingestion ids

pyproject.toml, src/encoded/schemas/file_processed.json, src/encoded/tests/data/inserts/file_processed.json, src/encoded/tests/data/inserts/sample_processing.json, src/encoded/tests/test_indexing.py, src/encoded/types/case.py, src/encoded/types/sample.py, src/encoded/types/variant.py
Update embeds for Case and SampleProcessing `files_processed` to include `variant_type` and `file_type` to better differentiate VCF files for Foursight and development, as well as `upload_key` for Case to facilitate Higlass identification of SV VCF to be used instead of BAM files. 
Also, add suggested `file_type` of "Higlass SV VCF" to be used for the above VCFs and new insert that can be used to test Higlass file identification.
=> Update embeds for SV bioinformatics workflow

pyproject.toml, src/encoded/schemas/note_interpretation.json, src/encoded/tests/test_types_note.py, src/encoded/types/note.py, src/encoded/types/variant.py
This incorporates data model changes that will allow modifying the strength or evidence level of ACMG rules during Interpretation.
In this PR:
- acmg_rules_invoked property added, which is an array of sub-embedded object containing the rule name and the strength
- acmg_guidelines, the old array of string property, is left in to avoid validation errors etc. should be removed in the future.
- acmg_rules_with_modifier calc prop added, which adds the strength to the rule name and returns one string
- unit test for calc prop added
- acmg_guidelines embed replaced with acmg_rules_invoked and acmg_rules_with_modifier
=> ACMG strength

pyproject.toml, src/encoded/schemas/case.json, src/encoded/static/components/static-pages/HomePage/UserDashboard.js
This PR is for hiding "inactive" status Cases from the main user dashboard.
- `&status!=inactive` added to Case search query on user dashboard
- status added as facet on Case search page, so that a user can click "Cases" and see all their cases, and can choose to hide inactive ones or not
- order numbers added to case facets
=> Hide inactive

docs/public/help/developer_facing_docs.md, pyproject.toml, src/encoded/tests/data/deploy-inserts/page.json, src/encoded/tests/data/deploy-inserts/static_section.json
As outlined in this [Trello ticket](https://trello.com/c/tMve1Mt0/109-minor-updates-to-cgaps-help-page), this PR adds a few new links for further information and changes the title of the page to "Informatics Documentation" from "Developer-Facing Documentation."
=> Update informatics documentation

pyproject.toml, src/encoded/schemas/case.json
Added `superceded_by` prop on case to indicate whether a case has been cloned, which contains the accession of the new case. I didn't want to make this a linkTo, primarily for indexing reasons. Additionally I didn't want to do a formal replacement as in 4DN because we don't necessarily want to make the original case inactive until the analysis is finished on the new case and variants are ingested.
=> Superceded prop

pyproject.toml, src/encoded/schemas/meta_workflow_run.json
We want to keep track of failed jobs to accurately compute costs of a MetaWorkflowRun. This PR adds the field `failed_jobs` to the scheme for this purpose.
=> Add failed_jobs to MetaWorkflowRun schema

pyproject.toml, src/encoded/submit_genelist.py
This PR implements a few small changes to gene list submission error messages based on recent open hours feedback. 
- When submitted gene not found, adds a reminder that only coding genes are in CGAP database
- When submitted gene not found, drops search on that gene to provide suggestions for possible alternatives
- When any error has occurred in processing, adds an explicit message that gene list was not created in the system
Remainder of feedback is front-end related and will come in separately.
=> Improve gene list submission messages

pyproject.toml, src/encoded/docs/extended_description_StructuralVariantSample_inheritance_mode.html, src/encoded/docs/extended_description_StructuralVariantSample_inheritance_mode_proband_only.html, src/encoded/docs/extended_description_VariantSample_inheritance_mode.html, src/encoded/docs/extended_description_VariantSample_inheritance_mode_probandonly.html, src/encoded/inheritance_mode.py, src/encoded/tests/test_inheritance_mode.py
The inheritance mode code needs handling for "unknown" sex. 
When sex is "U":
- genotypes/inheritance modes on autosomes stay the same
- genotypes on X or Y are labelled "ambiguous"
- inheritance modes on X or Y variants are labelled "Ambiguous due to missing sex determination"
=> U sex inhmode

pyproject.toml, src/encoded/static/components/item-pages/VariantSampleView/SampleTabBody.js, src/encoded/tests/test_types_variant_sample.py, src/encoded/types/variant.py
Since we're no longer generating BAM snapshots for mitochondrial variants, this PR updates the VariantSample `bam_snapshot` calculated property to remove it from mitochondrial variants. Additionally, if the property is not present on a VariantSample, the BAM Snapshot area (containing the link) within the annotation space's "Sample" tab is removed (e.g. compare this [X variant](http://fourfront-cgapdev.9wzadzju3p.us-east-1.elasticbeanstalk.com/variant-samples/253ad0f5-083f-4dfc-82de-4eb855d40376/) to this [mitochondrial one](http://fourfront-cgapdev.9wzadzju3p.us-east-1.elasticbeanstalk.com/variant-samples/2af827a0-ffda-4f21-a0f3-af55f7d2f057/#overview)).
=> Fix BAM snapshot for M variants

deploy/docker/local/docker_development.ini.template, pyproject.toml, src/encoded/commands/prepare_docker.py, src/encoded/types/file.py
* Include `s3_encrypt_key_id` among `upload_credentials` for data files.
* Change `prepare-docker` to accept an `--s3-encrypt-key-id` argument.
=> Include s3_encrypt_key_id among upload_credentials

pyproject.toml, src/encoded/tests/data/demo_inserts/project.json, src/encoded/tests/data/inserts/institution.json, src/encoded/tests/data/inserts/project.json, src/encoded/tests/data/inserts/user.json, src/encoded/tests/data/master-inserts/institution.json, src/encoded/tests/data/master-inserts/project.json, src/encoded/tests/data/master-inserts/user.json
We don't want certain users with inserts, like Joel and Arezou, to be added to every CGAP deployment (like MSA). I have moved them to the "inserts" directory out of "master-inserts" for now, so the inserts are still available if we need them.
=> reorganize user inserts

pyproject.toml, src/encoded/schemas/gene.json, src/encoded/schemas/variant_sample_list.json, src/encoded/static/components/item-pages/VariantSampleView/AnnotationSections.js
We update the schema for genes to allow for two new gene link-outs, to be manually patched after deployment. Gene inserts are also updated with the corresponding fields for new environments.
Additionally, we rename a sub-embedded property on VariantSampleLists to harmonize property names for both SNV and SV variant samples.
=> New gene link-outs

Dockerfile, deploy/docker/production/entrypoint.sh, package-lock.json, package.json, poetry.lock, pyproject.toml
- Changes needed to take latest Python Docker base image (python:3.7.12-slim-buster)
- Use waitress beta
- Change SPC pull to use HTTPS (not ssh)
- Generate session randomness at startup
=> March Security Update

.github/workflows/cypress-tests-production.yml, deploy/post_deploy_testing/cypress.json
Cypress tests broke due to URL switch; this just points the baseURLs for Cypress to new training account
=> April Cypress fixes

src/encoded/static/components/app.js, src/encoded/static/components/browse/variantSampleColumnExtensionMap.js, src/encoded/static/components/item-pages/CaseView/CaseViewEmbeddedVariantSampleSearchTable.js, src/encoded/static/components/item-pages/CaseView/VariantSampleSelection.js, src/encoded/static/components/item-pages/components/child-window-controls.js, src/encoded/static/libs/react-middleware.js, src/encoded/static/store.js, src/encoded/types/structural_variant.py, src/encoded/types/variant.py
Links from InterpretationTab and Search Result Column are now buttons to prevent people from right-clicking "Open in new tab" and forcing UI to manage the child tabs instead (preserving window.opener/childWindow communication).
~~TODO Still: Display titles~~ done.
=> Open child tabs, convert links to buttons.

pyproject.toml, src/encoded/tests/data/demo_inserts/variant_sample.json, src/encoded/tests/data/master-inserts/user.json
Remove departed CGAP members from inserts. Members have had their User items set to `status: deleted` on all deployed environments.
=> Remove Departed Admins

.flake8, deploy/docker/local/entrypoint.sh, deploy/docker/production/entrypoint_deployment.sh, pyproject.toml, src/encoded/commands/clear_db_es_contents.py, src/encoded/tests/test_clear_db_es_contents.py, src/encoded/tests/test_clear_es_db_contents.py
Adjustments to clear-db-es-contents to make arguments more intelligible and error messages more clear.
Instead of `--env <envname>` this wants you to supply `--only-if-env <env>` or `--only-if-envs <env1>,<env2>,...`
A `--confirm` and `--no-confirm` controls whether you are interactively queried for confirmation. The default is not to prompt if you provide `--only-if-env` or `--only-if-envs`, and otherwise to prompt.
=> Syntax makeover for clear-db-es-contents

CHANGELOG.rst, Dockerfile, development.ini.template, pyproject.toml, test.ini.template
@alexkb0009 reported a problem ([C4-907](https://hms-dbmi.atlassian.net/browse/C4-907)) in the `.ini` file creation done by `prepare-local-dev`. This fixes that.
I'm also including some cosmetic changes to the `Dockerfile`.
=> Fix problems in development.init.template and test.ini.template

Dockerfile, package-lock.json, package.json, pyproject.toml
- Remove duplicated entry for Cypress causing it to be packaged with Docker
- Update package-lock.json
- There is a .cache folder that npm uses and duplicates the node_modules unnecessarily, I realized it when reviewing the ECR scans and the cache paths showed vulnerabilities - removes this
=> Remove Cypress from devDependencies

.github/workflows/static-checks.yml, CHANGELOG.rst, Makefile, poetry.lock, pyproject.toml, pytest.ini, src/encoded/tests/test_misc.py
* Uses `dcicutils ^5.1.0` (and updated `snovault ^6.0.7` that's compatible with that)
* Raises error on changelog inconsistency.
* Adds a workflow to check static things like changelog.
Note: The new workflow shouldn't need database setup, but that's because we have server fixtures that span the whole set of tests that do database setup/cleanup. We might want to make an env variable that can suppress that so that we don't have to wait for a db install. It's not hugely slow, at least.
=> Adjustments to changelog handling

CHANGELOG.rst, pyproject.toml, src/encoded/submit.py, src/encoded/tests/data/inserts/file_format.json, src/encoded/tests/test_submit.py
Here, we make some minor bug fixes to the submission code to remove errors around the use of `conjoined_list`. Also, we update an insert to permit FASTQ file submissions when default inserts loaded.
=> Submission bug fixes

CHANGELOG.rst, pyproject.toml, src/encoded/schemas/file.json, src/encoded/schemas/file_fastq.json, src/encoded/schemas/file_processed.json, src/encoded/schemas/mixins.json
Here, we move the `paired_end` property onto the abstract File item so it is available to all child items.
=> File Paired-end Property

CHANGELOG.rst, pyproject.toml, src/encoded/submit.py, src/encoded/tests/test_submit.py
Here, we update `submit.py` to add the `paired_end` property to submitted FASTQs. Determination of the paired end was included in a previous refactor of parsing submitted files, but this property addition was dropped accidentally at that time.
=> Add Paired End Property to FASTQ on Submission

CHANGELOG.rst, pyproject.toml, src/encoded/static/components/forms/ExcelSubmissionView.js, src/encoded/static/components/item-pages/CaseView/index.js, src/encoded/static/components/util/hooks.js, src/encoded/static/components/util/index.js, src/encoded/static/scss/encoded/modules/_item-pages.scss
**Changelog:**
- Allows case information to be shown/hidden via a toggle
- Default state is dependent upon tab selected (dotPath); accessioning tab will load case info open, other tabs will keep it closed on load
- ~Note to self: need to add `e.stopPropagation` to the copyWrrapper, so the copy accession button doesn't trigger open/closing~ added prop (functionality needs to be added in SPC update/release)
- Create a utility file for storing reusable custom React hooks (+ move pre-existing ones there)
- Might be some formatting changes throughout a couple of files (used format document at some point in vscode)
**Deployment Notes:**
- ~Currently deployed to [cgap-devtest](https://cgap-devtest.hms.harvard.edu/)~ Not anymore
**Relevant Trello Ticket:** …
=> Bch case drawer

CHANGELOG.rst, pyproject.toml, src/encoded/static/components/item-pages/CaseView/CaseStats.js
**Changelog:**
- Sorts `case.sample_processing.families.family_phenotypic_features` and `case.individual.phenotypic_features` before rendering via CaseStats
**Screenshot:**
[![Image from Gyazo](https://i.gyazo.com/4d8aee3b91895bd784378517b36485cc.png)](https://gyazo.com/4d8aee3b91895bd784378517b36485cc)
=> Sort alphabetically phenotypic features

src/encoded/__init__.py
This correction ensures that the 'allowedConnections' property of the /auth0_config endpoint is an array; split on a comma-separated string (typically in GAC as 'ENCODED_AUTH0_ALLOWED_CONNECTIONS').
=> Corrected /auth0_config endpoint to return array for allowedConnections

CHANGELOG.rst, pyproject.toml, src/encoded/submit.py
Fix in parse_exception in submit.py to catch/ignore additional/new error message from normalize_links in snovault/schema_validation.py; manifested as error from submit-metadata.
=> Fix in submit.py for new error message from snovault.schema_validation

CHANGELOG.rst, README.rst, pyproject.toml
This overhauls the [README.rst](https://github.com/dbmi-bgm/cgap-portal/blob/kmp_update_readme/README.rst) in various ways:
* Add a reference to new `cgap-governance` repo.
* Clean up some of the structure and text.
* Remove stale references to beanstalks.
* Remove stale references to beanstalk deployment environments.
=> Modernize README (C4-1037)

CHANGELOG.rst, pyproject.toml, src/encoded/tests/data/inserts/institution.json
Someone removed Dana's user record from master inserts, but there was still a reference to it in another data file; without this fix make deploy1 fails on inserts.
=> Fixed up data for previous removal of Dana's user record.
